name: Face Recognition CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # Install system libraries required for face-recognition (dlib)
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential libopenblas-dev liblapack-dev

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Syntax Check for your files
    - name: Syntax Check
      run: |
        python -m py_compile face.py
        python -m py_compile convert_csv_to_excel.py

    # Code formatting check (DevOps standard)
    - name: Install Black
      run: pip install black

    - name: Auto Format Code
      run: |
        pip install black
        black .

    # Build Docker image
    - name: Build Docker Image
      run: docker build -t face-attendance .